provider:
  name: aws

sources:
  - ingress

policy: upsert-only
registry: txt
txtOwnerId: kube-rca-dev-eks

domainFilters:
  - kkamji.net

extraArgs:
  aws-zone-type: public

serviceAccount:
  create: true
  name: external-dns
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::376129852049:role/kube-rca-dev-external-dns
